# Generated by Django 5.1.3 on 2024-11-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_employee_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_count',
        ),
    ]
