# Generated by Django 5.1.3 on 2024-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_employee_task_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус False - задача выполняется, статус True - задачавыполнена'),
        ),
    ]
